/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        cherry: '#2D014B',
        'cherry-2': '#081C4F',
        outline: '#E3E8F1',
        'outline-2': '#CBD5E1',
        light: '#F9FBFC',
        primary: '#00CDB4',
        'black-k': '#2E3A44',
        'black-6': '#5B6785',
        'abu-tipis': '#F6F6F6',
        neutural: '#64748B',
        'dark-3': '#454545',
        'dark-4': '#5C5C5C',
        'dark-5': '#737373',
        'dark-6': '#A8A8A8',
        'dark-7': '#CACACA',
        'dark-8': '#EDEDED',
        'dark-11': '#C1C1C1',
        fill: '#5A5A5A',
        placeholder: '#888888',
        'title-active': '#1A1A1A',
        'light-gray': '#C0C6D4',
        title: '#475569',
        'light-primary': '#E6FAF8',
        kuning: '#FDBE0F',
        'kuning-3': '#FFA12E',
        'green-2': '#30DF3F',
        'purple-2': '#8A6F9C',
        'purple-3': '#6F83D8',
        'background-3': '#F3F3F3',
      },
      fontSize: {
        xxs: '10px',
        '3xl': '32px',
      },
      fontFamily: {
        mulish: ['Mulish'],
        merriweather: ['Merriweather'],
      },
    },
  },
  plugins: [
    require('tailwindcss-font-inter'),
    require('tailwind-scrollbar-hide'),
    require('@tailwindcss/line-clamp'),
    require('tailwindcss-debug-screens'),
    require('daisyui'),
  ],
};
